// AUTO-GENERATED by scripts/pull-types.ts. Do not edit.
// Run `bun run db:types` after schema changes.
//
// HAND-CRAFTED STUB: this file was written by hand to match the migrations in
// supabase/migrations/ before the local Supabase stack was available. Once
// `supabase start` is running, replace this file with `bun run db:types`.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          role: Database['public']['Enums']['user_role'];
          display_name: string | null;
          locale: 'th' | 'en';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          role?: Database['public']['Enums']['user_role'];
          display_name?: string | null;
          locale?: 'th' | 'en';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          role?: Database['public']['Enums']['user_role'];
          display_name?: string | null;
          locale?: 'th' | 'en';
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      current_role: { Args: Record<string, never>; Returns: Database['public']['Enums']['user_role'] };
      is_owner_or_dev: { Args: Record<string, never>; Returns: boolean };
      is_dev: { Args: Record<string, never>; Returns: boolean };
    };
    Enums: {
      user_role: 'customer' | 'owner' | 'dev';
    };
    CompositeTypes: { [_ in never]: never };
  };
}
