// AUTO-GENERATED by scripts/pull-types.ts. Do not edit.
// Run `bun run db:types` after schema changes.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      discount_codes: {
        Row: {
          active: boolean
          code: string
          created_at: string
          ends_at: string
          id: string
          kind: string
          max_uses: number | null
          min_subtotal_thb: number
          starts_at: string
          updated_at: string
          uses: number
          value: number
          version: number
        }
        Insert: {
          active?: boolean
          code: string
          created_at?: string
          ends_at: string
          id?: string
          kind: string
          max_uses?: number | null
          min_subtotal_thb?: number
          starts_at: string
          updated_at?: string
          uses?: number
          value: number
          version?: number
        }
        Update: {
          active?: boolean
          code?: string
          created_at?: string
          ends_at?: string
          id?: string
          kind?: string
          max_uses?: number | null
          min_subtotal_thb?: number
          starts_at?: string
          updated_at?: string
          uses?: number
          value?: number
          version?: number
        }
        Relationships: []
      }
      order_events: {
        Row: {
          actor: string
          created_at: string
          id: string
          order_id: string
          payload: Json
          type: string
        }
        Insert: {
          actor: string
          created_at?: string
          id?: string
          order_id: string
          payload?: Json
          type: string
        }
        Update: {
          actor?: string
          created_at?: string
          id?: string
          order_id?: string
          payload?: Json
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: "order_events_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      order_items: {
        Row: {
          created_at: string
          id: string
          is_preorder: boolean
          line_total_thb: number
          order_id: string
          product_snapshot: Json
          qty: number
          unit_price_thb: number
          variant_id: string | null
        }
        Insert: {
          created_at?: string
          id?: string
          is_preorder?: boolean
          line_total_thb: number
          order_id: string
          product_snapshot: Json
          qty: number
          unit_price_thb: number
          variant_id?: string | null
        }
        Update: {
          created_at?: string
          id?: string
          is_preorder?: boolean
          line_total_thb?: number
          order_id?: string
          product_snapshot?: Json
          qty?: number
          unit_price_thb?: number
          variant_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "order_items_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_items_variant_id_fkey"
            columns: ["variant_id"]
            isOneToOne: false
            referencedRelation: "variants"
            referencedColumns: ["id"]
          },
        ]
      }
      orders: {
        Row: {
          created_at: string
          currency: string
          customer_email: string
          customer_id: string | null
          delivered_at: string | null
          discount_thb: number
          estimated_delivery_date: string | null
          id: string
          last_event_id: string | null
          locale: string
          notes_internal: string | null
          notes_to_buyer: string | null
          number: string
          paid_at: string | null
          payment_charge_id: string | null
          payment_method: string | null
          payment_provider: string
          ship_status: Database["public"]["Enums"]["ship_status"]
          shipped_at: string | null
          shipping_address: Json
          shipping_thb: number
          status: Database["public"]["Enums"]["order_status"]
          subtotal_thb: number
          total_thb: number
          tracking_carrier: string | null
          tracking_number: string | null
          tracking_url: string | null
          updated_at: string
          version: number
        }
        Insert: {
          created_at?: string
          currency?: string
          customer_email: string
          customer_id?: string | null
          delivered_at?: string | null
          discount_thb?: number
          estimated_delivery_date?: string | null
          id?: string
          last_event_id?: string | null
          locale: string
          notes_internal?: string | null
          notes_to_buyer?: string | null
          number: string
          paid_at?: string | null
          payment_charge_id?: string | null
          payment_method?: string | null
          payment_provider: string
          ship_status?: Database["public"]["Enums"]["ship_status"]
          shipped_at?: string | null
          shipping_address: Json
          shipping_thb?: number
          status?: Database["public"]["Enums"]["order_status"]
          subtotal_thb: number
          total_thb: number
          tracking_carrier?: string | null
          tracking_number?: string | null
          tracking_url?: string | null
          updated_at?: string
          version?: number
        }
        Update: {
          created_at?: string
          currency?: string
          customer_email?: string
          customer_id?: string | null
          delivered_at?: string | null
          discount_thb?: number
          estimated_delivery_date?: string | null
          id?: string
          last_event_id?: string | null
          locale?: string
          notes_internal?: string | null
          notes_to_buyer?: string | null
          number?: string
          paid_at?: string | null
          payment_charge_id?: string | null
          payment_method?: string | null
          payment_provider?: string
          ship_status?: Database["public"]["Enums"]["ship_status"]
          shipped_at?: string | null
          shipping_address?: Json
          shipping_thb?: number
          status?: Database["public"]["Enums"]["order_status"]
          subtotal_thb?: number
          total_thb?: number
          tracking_carrier?: string | null
          tracking_number?: string | null
          tracking_url?: string | null
          updated_at?: string
          version?: number
        }
        Relationships: []
      }
      payment_settings: {
        Row: {
          account_label: string | null
          id: string
          instructions: Json
          promptpay_qr_path: string | null
          updated_at: string
        }
        Insert: {
          account_label?: string | null
          id?: string
          instructions?: Json
          promptpay_qr_path?: string | null
          updated_at?: string
        }
        Update: {
          account_label?: string | null
          id?: string
          instructions?: Json
          promptpay_qr_path?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      payment_slips: {
        Row: {
          id: string
          order_id: string
          reject_reason: string | null
          reviewed_at: string | null
          reviewed_by: string | null
          status: string
          storage_path: string
          uploaded_at: string
        }
        Insert: {
          id?: string
          order_id: string
          reject_reason?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: string
          storage_path: string
          uploaded_at?: string
        }
        Update: {
          id?: string
          order_id?: string
          reject_reason?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: string
          storage_path?: string
          uploaded_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "payment_slips_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      processed_webhook_events: {
        Row: {
          event_id: string
          id: string
          order_id: string | null
          provider: string
          received_at: string
        }
        Insert: {
          event_id: string
          id?: string
          order_id?: string | null
          provider: string
          received_at?: string
        }
        Update: {
          event_id?: string
          id?: string
          order_id?: string | null
          provider?: string
          received_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "processed_webhook_events_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      product_images: {
        Row: {
          alt: Json
          created_at: string
          id: string
          product_id: string
          sort: number
          storage_path: string
          url_1600: string
          url_400: string
          url_800: string
        }
        Insert: {
          alt?: Json
          created_at?: string
          id?: string
          product_id: string
          sort?: number
          storage_path: string
          url_1600: string
          url_400: string
          url_800: string
        }
        Update: {
          alt?: Json
          created_at?: string
          id?: string
          product_id?: string
          sort?: number
          storage_path?: string
          url_1600?: string
          url_400?: string
          url_800?: string
        }
        Relationships: [
          {
            foreignKeyName: "product_images_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      products: {
        Row: {
          base_price_thb: number
          category: string | null
          created_at: string
          description: Json
          hero_image_id: string | null
          id: string
          is_featured: boolean
          is_preorder: boolean
          name: Json
          preorder_ship_date: string | null
          slug: string
          status: Database["public"]["Enums"]["product_status"]
          updated_at: string
          version: number
          weight_grams: number
        }
        Insert: {
          base_price_thb: number
          category?: string | null
          created_at?: string
          description?: Json
          hero_image_id?: string | null
          id?: string
          is_featured?: boolean
          is_preorder?: boolean
          name: Json
          preorder_ship_date?: string | null
          slug: string
          status?: Database["public"]["Enums"]["product_status"]
          updated_at?: string
          version?: number
          weight_grams?: number
        }
        Update: {
          base_price_thb?: number
          category?: string | null
          created_at?: string
          description?: Json
          hero_image_id?: string | null
          id?: string
          is_featured?: boolean
          is_preorder?: boolean
          name?: Json
          preorder_ship_date?: string | null
          slug?: string
          status?: Database["public"]["Enums"]["product_status"]
          updated_at?: string
          version?: number
          weight_grams?: number
        }
        Relationships: [
          {
            foreignKeyName: "products_hero_image_fk"
            columns: ["hero_image_id"]
            isOneToOne: false
            referencedRelation: "product_images"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          created_at: string
          display_name: string | null
          id: string
          locale: string
          role: Database["public"]["Enums"]["user_role"]
          updated_at: string
        }
        Insert: {
          created_at?: string
          display_name?: string | null
          id: string
          locale?: string
          role?: Database["public"]["Enums"]["user_role"]
          updated_at?: string
        }
        Update: {
          created_at?: string
          display_name?: string | null
          id?: string
          locale?: string
          role?: Database["public"]["Enums"]["user_role"]
          updated_at?: string
        }
        Relationships: []
      }
      sheet_sync_rejects: {
        Row: {
          attempted_value: string | null
          column_name: string
          created_at: string
          id: string
          reason: string
          row_pk: string
          run_id: string
          table_name: string
        }
        Insert: {
          attempted_value?: string | null
          column_name: string
          created_at?: string
          id?: string
          reason: string
          row_pk: string
          run_id: string
          table_name: string
        }
        Update: {
          attempted_value?: string | null
          column_name?: string
          created_at?: string
          id?: string
          reason?: string
          row_pk?: string
          run_id?: string
          table_name?: string
        }
        Relationships: [
          {
            foreignKeyName: "sheet_sync_rejects_run_id_fkey"
            columns: ["run_id"]
            isOneToOne: false
            referencedRelation: "sheet_sync_runs"
            referencedColumns: ["id"]
          },
        ]
      }
      sheet_sync_runs: {
        Row: {
          error: string | null
          finished_at: string | null
          id: string
          rows_applied: number
          rows_pulled: number
          rows_rejected: number
          started_at: string
          status: string
          trigger: string
        }
        Insert: {
          error?: string | null
          finished_at?: string | null
          id?: string
          rows_applied?: number
          rows_pulled?: number
          rows_rejected?: number
          started_at?: string
          status: string
          trigger: string
        }
        Update: {
          error?: string | null
          finished_at?: string | null
          id?: string
          rows_applied?: number
          rows_pulled?: number
          rows_rejected?: number
          started_at?: string
          status?: string
          trigger?: string
        }
        Relationships: []
      }
      shipping_zones: {
        Row: {
          code: string
          countries: string[]
          created_at: string
          flat_rate_thb: number
          id: string
          is_active: boolean
          name: Json
          sort: number
          updated_at: string
          version: number
        }
        Insert: {
          code: string
          countries: string[]
          created_at?: string
          flat_rate_thb: number
          id?: string
          is_active?: boolean
          name: Json
          sort?: number
          updated_at?: string
          version?: number
        }
        Update: {
          code?: string
          countries?: string[]
          created_at?: string
          flat_rate_thb?: number
          id?: string
          is_active?: boolean
          name?: Json
          sort?: number
          updated_at?: string
          version?: number
        }
        Relationships: []
      }
      variant_options: {
        Row: {
          id: string
          name: string
          product_id: string
          sort: number
          values: string[]
        }
        Insert: {
          id?: string
          name: string
          product_id: string
          sort?: number
          values: string[]
        }
        Update: {
          id?: string
          name?: string
          product_id?: string
          sort?: number
          values?: string[]
        }
        Relationships: [
          {
            foreignKeyName: "variant_options_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      variants: {
        Row: {
          created_at: string
          id: string
          is_active: boolean
          option_values: Json
          preorder_cap: number | null
          preorder_count: number
          preorder_enabled: boolean
          price_thb: number | null
          product_id: string
          sku: string
          stock_available: number
          stock_reserved: number
          updated_at: string
          version: number
        }
        Insert: {
          created_at?: string
          id?: string
          is_active?: boolean
          option_values: Json
          preorder_cap?: number | null
          preorder_count?: number
          preorder_enabled?: boolean
          price_thb?: number | null
          product_id: string
          sku: string
          stock_available?: number
          stock_reserved?: number
          updated_at?: string
          version?: number
        }
        Update: {
          created_at?: string
          id?: string
          is_active?: boolean
          option_values?: Json
          preorder_cap?: number | null
          preorder_count?: number
          preorder_enabled?: boolean
          price_thb?: number | null
          product_id?: string
          sku?: string
          stock_available?: number
          stock_reserved?: number
          updated_at?: string
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "variants_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      waitlist_entries: {
        Row: {
          created_at: string
          email: string
          id: string
          locale: string
          notified_at: string | null
          variant_id: string
        }
        Insert: {
          created_at?: string
          email: string
          id?: string
          locale: string
          notified_at?: string | null
          variant_id: string
        }
        Update: {
          created_at?: string
          email?: string
          id?: string
          locale?: string
          notified_at?: string | null
          variant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "waitlist_entries_variant_id_fkey"
            columns: ["variant_id"]
            isOneToOne: false
            referencedRelation: "variants"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      current_role: {
        Args: never
        Returns: Database["public"]["Enums"]["user_role"]
      }
      is_dev: { Args: never; Returns: boolean }
      is_owner_or_dev: { Args: never; Returns: boolean }
    }
    Enums: {
      order_status:
        | "awaiting_payment"
        | "awaiting_verification"
        | "paid"
        | "failed"
        | "cancelled"
        | "refunded"
      product_status: "draft" | "active" | "archived"
      ship_status:
        | "pending"
        | "awaiting_stock"
        | "preparing"
        | "shipped"
        | "delivered"
      user_role: "customer" | "owner" | "dev"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      order_status: [
        "awaiting_payment",
        "awaiting_verification",
        "paid",
        "failed",
        "cancelled",
        "refunded",
      ],
      product_status: ["draft", "active", "archived"],
      ship_status: [
        "pending",
        "awaiting_stock",
        "preparing",
        "shipped",
        "delivered",
      ],
      user_role: ["customer", "owner", "dev"],
    },
  },
} as const

