#!/usr/bin/env bun
// Generate TypeScript types from the local Supabase project.
// Usage: bun run db:types
// Requires: supabase CLI installed AND `supabase start` already booted locally.

import { spawnSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

const result = spawnSync(
  'supabase',
  ['gen', 'types', 'typescript', '--local', '--schema', 'public'],
  { encoding: 'utf8' },
);

if (result.status !== 0) {
  console.error(result.stderr);
  process.exit(result.status ?? 1);
}

const header =
  '// AUTO-GENERATED by scripts/pull-types.ts. Do not edit.\n' +
  '// Run `bun run db:types` after schema changes.\n\n';

writeFileSync('src/db/types.gen.ts', header + result.stdout);
console.log('Wrote src/db/types.gen.ts');
